language: ruby
rvm:
  - 2.5.0
services:
    - postgresql
addons:
    postgresql: '9.6'
before_script:
  - psql -c 'create database todayilearned_test;' -U postgres
after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "bundle exec cap production deploy"
