language: ruby
rvm:
  - 2.5.0
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - psql -c 'create database todayilearned_test;' -U postgres
