default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todayilearned_development
  username: postgres

test:
  <<: *default
  username: postgres
  database: todayilearned_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: APP_PRODUCTION
  username: egor
  url: localhost
  password: <%= ENV['DATABASE_PASSWORD'] %>
